### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by javache** [ZeusWPI/FK-enrolment#1]
* ~~Registreren CNAME registratie.fkgent.be~~
* ~~CAS-registratie~~
* ~~Unicorn init-scriptje toevoegen~~
* Test-versie deployen onder /testing voor API-devs
* ~~Automatically expire sessions~~
* Deploy with Capistrano
* Add delayed_job-worker to Procfile

**Comment by Silox** [comment]
Yes, this has been fixed.
