### ISSUE TITLE
Export function does not have a select year field

### ISSUE THREAD

**Issue by Thoge** [ZeusWPI/FK-enrolment#43]
It is not possible to export past years to excel.

The vote's for the FK AV will be calculated on the member at the end of the past year. This issue is critical.

**Comment by Silox** [comment]
It's a feature, not a bug. Currently `club.members` is exported while only the set of members returned from the filter should be exported.

**Comment by Silox** [comment]
#44 now mirrors the filter changes into the data export when refreshing an export. So when filtering by year and refreshing the export, the new xls will contain the same data as in the table below.
