### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/FK-enrolment#86]
Recently, a pull request was made to this repository (#85). I am not happy at all with the way this was handled. With best intentions, I gave my remarks about the code, encouraging what I think of as best practices. However, the author refused to even acknowledge my review, and decided to throw some profanity my way (75e8fd52acb7a50c0eb006b8b7c8af62be708c4d). After this he barked at me in person that he would just force push to master from now on. I think an offense like this should not be treated lightly, and toxic contributors like this should be removed from the project. A proper code of conduct should be put in place to avoid this kind of situation in the future.

**Comment by iasoon** [comment]
cc @wschella

**Comment by VandorpeDavid** [comment]
I'd like to make a suggestion: keep your reviews to the point and don't troll in them.

**Comment by R13N** [comment]
I see only one solution. :fire: :gun: :policeman: :cactus:

**Comment by VandorpeDavid** [comment]
>>> After this he barked at me in person that he would just force push to master from now on.

Liar, this was @R13N

**Comment by wschella** [comment]
A decent code of conduct would also specify to respect the author, his intentions, and his time; as to not burden the commitment of his contributions more then necessary.  In respect to this, I accuse @feliciaan of malicious compliance to his own ethics and moral, resulting in both him and @VandorpeDavid to lose much needed sanity and energy. All of which could be spend on providing improvements to this codebase of a more qualitative nature then the changes suggested. @VandorpeDavid proclaimed not guilty.
